services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - nest-network

  test:
    build: .
    container_name: nestjs-app-test
    env_file:
      - .env
    command: npm run test
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nest-network

  db:
    image: postgres:16
    container_name: nest-postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-network

networks:
  nest-network:

volumes:
  pgdata:
